### ISSUE TITLE
🐛 Broken REST Routes

### ISSUE THREAD

**Issue by jim380** [sedaprotocol/seda-chain#159]
## Overview

There's at least one REST route that's currently broken. Likely more. Some more urgent, some less. We need to fix them based on priority:
- `/cosmos/tx/v1beta1/txs?events=message.sender='seda...'`

## Investigation
After some investigation the `/txs` route broke exactly in commit [`45395245601a363af836a3bb4a59a9385d4991cb`](https://github.com/sedaprotocol/seda-chain/commit/45395245601a363af836a3bb4a59a9385d4991cb). 

### Before Upgrading to SDK v0.50
`/cosmos/tx/v1beta1/txs?events=message.sender='seda...'` worked normally.
```
http://localhost:1317/cosmos/tx/v1beta1/txs?events=message.sender='seda1e32g7uv8pw7jrxdhtz7adxfws0vw6u9gzcxccq'
```
✅ ![image](https://github.com/sedaprotocol/seda-chain/assets/31609693/61d5c91f-d042-46c3-b5b0-df9c4c771090)

### After Upgrading to SDK v0.50
Check out the commit prior, i.e. [`b4b6ed7acd017ebbccfe1a62cbdec053275a6847`](https://github.com/sedaprotocol/seda-chain/commit/b4b6ed7acd017ebbccfe1a62cbdec053275a6847). And you will see the route no longer works.
```
http://localhost:1317/cosmos/tx/v1beta1/txs?events=message.sender='seda1e32g7uv8pw7jrxdhtz7adxfws0vw6u9gzcxccq'
```
🔴 ![image](https://github.com/sedaprotocol/seda-chain/assets/31609693/7a93bf2b-822f-444a-b680-2adb04254e34)

**Comment by hacheigriega** [comment]
The correct route is now `/cosmos/tx/v1beta1/txs?query=message.sender='seda...'`

https://github.com/cosmos/cosmos-sdk/pull/14758

**Comment by yerycs** [comment]
Hi @hacheigriega  @Thomasvdam 
`/cosmos/tx/v1beta1/txs?query=message.sender='seda...'`
Above query returns following error message.
```
{
    "code": 3,
    "message": "must declare at least one event to search",
    "details": []
}
```
Could you let me know how to use `query` correctly?

**Comment by Thomasvdam** [comment]
@yerycs I'm not sure which host you're trying to reach, but most likely they're using some proxying service that is not forwarding the query parameters. We had our proxy configured incorrectly and observed the same issue, so if you were using our endpoints this should be fixed.

**Comment by yerycs** [comment]
@Thomasvdam Please let me know your endpoints

**Comment by hacheigriega** [comment]
Reopening the issue because it is indeed very confusing because the documentation is all incorrect. Looks like we have to update `openapi.yml`. 

@yerycs Sorry I missed your comment. Which network are you trying to connect to? Testnet or Mainnet?
