### ISSUE TITLE
🐛 Remove $HOME Override in Dockerfile

### ISSUE THREAD

**Issue by jim380** [sedaprotocol/seda-chain#160]
## Overview

Currently in multiple places we override the `$HOME` env variable in dockerfiles. What this is doing essentially, is forcing the node operators who use our Dockerfiles to pass in a custom home directory upon running:
```
$ seda-chaind start --home <home_dir>
```
If `--home` is not passed, it defaults to the `$HOME` that we overrode prematurely in the Dockerfile, and the operator would see:
```
panic: open /seda-chain/.seda-chain/config/genesis.json: no such file or directory
```
`$HOME` should always be the default set by the operating system that the operator chooses to run `seda-chaind` on, typically `/root`. This is the default behavior by the sdk and we should respect that.

**Comment by gluax** [comment]
For now, I am moving this issue to the backlog while it's not a priority and #198.
