### ISSUE TITLE
🐛 Error when importing an exported state

### ISSUE THREAD

**Issue by hacheigriega** [sedaprotocol/seda-chain#180]
## 🐛 Bug Report

A routine sequence of exporting from a chain at a certain height and importing and starting it is resulting in an error. To reproduce the issue, ssh into one of the devnet nodes (preferably the second node), stop the daemon, and export at height 20000:
```
$ sudo systemctl stop seda-node.service
$ cosmovisor run export --height 20000 --output-document export_state_20000
$ sudo systemctl start seda-node.service # restart the daemon
```

Now, on a local machine, try starting a node from exported state:
```
$ git checkout v0.0.4 # devnet version
$ make build
$ ./build/seda-chaind join testnode --network devnet
$ cp export_state_20000 ~/.seda-chain/config/genesis.json # copy the export file to the local chain directory
$ ./build/seda-chaind start
```

My attempts fail due to the following error during the genesis initialization process:
```
panic: client state type 09-localhost is not registered on the allowlist
```

**Comment by hacheigriega** [comment]
Same problem with testnet

**Comment by hacheigriega** [comment]
The issue is that a localhost client is automatically generated no matter what. Therefore, when we exclude localhost from the allowed client type list in the IBC genesis parameter, we end up with this error. I think an easy fix to this issue would be to just add back `"07-tendermint"` to the allowed client type list. Any thought? @jim380  @mariocao @FranklinWaller 

As soon as chain starts, the following client object is created in the state:
```
"clients": [
          {
            "client_id": "09-localhost",
            "client_state": {
              "@type": "/ibc.lightclients.localhost.v2.ClientState",
              "latest_height": {
                "revision_number": "0",
                "revision_height": "0"
              }
            }
          }
        ],
```

**Comment by jim380** [comment]
We checked our genesis params with other chains' and ours is indifferent to theirs. Will continue investigating.

**Comment by hacheigriega** [comment]
It's created by IBC core module during the `InitGenesis` process. Specifically, the method `CreateLocalhostClient()` is called.

**Comment by jim380** [comment]
Found the issue. We didn't migrate 09-localhost in the last chain upgrade. When done correctly It'd look like the following
![image](https://github.com/sedaprotocol/seda-chain/assets/31609693/51e2f65e-51ce-4da0-a2ed-5b283afd6578)

**Comment by jim380** [comment]
Might be multiple spots broken, as it happens on a local deploy -> export -> import as well per @hacheigriega.

**Comment by hacheigriega** [comment]
We decided to just add localhost to the allowed list in the genesis parameter.
