### ISSUE TITLE
✨ Implement clawback continuous vesting account

### ISSUE THREAD

**Issue by hacheigriega** [sedaprotocol/seda-chain#194]
## ✨ Feature

Implement a custom vesting account called `ClawbackContinuousVestingAccount` which wraps the SDK's `ContinuousVestingAccount` to provide an additional feature for cancelling a vesting stream.

- `tx create-vesting-account [to_address] [amount] [end_time]` for creating a `ClawbackContinuousVestingAccount`
  - The account must not already exist
  - The "from address" is registered as the newly created vesting account's funder, which is stored in the module keeper.

- `tx clawback [address]`
  - The funds that are still vesting are sent back to the funder's address
  - The funder corresponding to the vesting account is removed from the vesting module's store.

**Comment by jim380** [comment]
Vesting coins can't be spent but can be delegated. So when doing a clawback, we can't just send them back to the funder without checking if any of them are delegated.
