### ISSUE TITLE
🐛 Chain command building fails (at runtime) without AutoCLI code in staking

### ISSUE THREAD

**Issue by hacheigriega** [sedaprotocol/seda-chain#199]
## 🐛 Bug Report

Without the `AutoCLI()` function that has been copied from the SDK staking module to the custom staking module, the chain panics due to a duplicate flag issue in the `EnhanceRootCommandWithBuilder()` call in `root.go`. The issue seems to be coming from the staking's historical info query argument "height" being misinterpreted as a flag. So it may be an issue with the autocli library code, but it would be nice to have a cleaner solution.

**Comment by gluax** [comment]
I tried a few things with no success. I opened an issue on the cosmos-sdk for this [here](https://github.com/cosmos/cosmos-sdk/issues/19778).
