### ISSUE TITLE
🔧 Deploy devnet with DR functionality

### ISSUE THREAD

**Issue by mariocao** [sedaprotocol/seda-chain#221]
## 🔧 Chore

Deploy a new devnet network with the latest changes on re-wiring custom modules for DR execution.
The network should have the DR and staking contracts deployed.
It should be done as a network upgrade.

## Motivation

This devnet will allow the team to continue the development on DR features.

**Comment by hacheigriega** [comment]
Done! https://github.com/sedaprotocol/seda-networks/blob/main/devnet/genesis.json
