### ISSUE TITLE
🔧 Investigate CGO Usage for WASMVM

### ISSUE THREAD

**Issue by gluax** [sedaprotocol/seda-chain#23]
## 🔧 Chore

We may possibly not need CGO for the [WASMVM](https://github.com/CosmWasm/wasmvm) usage.

## Motivation

If we don't need CGO the build process would be a lot easier and simpler for people to work with. Could also simplify the CI. The linked repo has instructions on not using CGO. Unsure if this means we wouldn't need it in the end or not.

**Comment by gluax** [comment]
Priority change due to affecting how we deal with the WASM shared object library file for upgrades.

**Comment by mariocao** [comment]
Timeboxed to half a day
