### ISSUE TITLE
🔧 Create and test delegation genesis transactions

### ISSUE THREAD

**Issue by hacheigriega** [sedaprotocol/seda-chain#236]
## 🔧 Chore

The goal is to include delegation transactions at genesis along with create-validator transactions that set up the initial validator set.

We will probably have to create a separate gentx-like command for this purpose. Once implemented, it must be tested with a devnet relaunch.

**Comment by jim380** [comment]
Let me know how I can help

**Comment by DeshErBojhaa** [comment]
We've decided not to follow this approach during the launch.
