### ISSUE TITLE
🔧 Support snapshot and state sync

### ISSUE THREAD

**Issue by hacheigriega** [sedaprotocol/seda-chain#239]
## 🔧 Chore

Currently we rely on Lavender.Five's snapshot, but this issue calls for providing snapshots ourselves. Joining testnet through state sync is also failing under the following configuration:

```
[statesync]
enable = true
rpc_servers = "https://rpc.testnet.seda.xyz:443,18.171.36.35:26657"
trust_height = 452688
trust_hash = "015AFE5D0909B16889078A9901EA54466EF7A304A5F44134C6BCA05E583DB8BA"
trust_period = "168h0m0s"
```

where the trusted block height and hash are obtained by 
```
curl -s https://rpc.testnet.seda.xyz:443/block | jq -r '.result.block.header.height + "\n" + .result.block_id.hash'
```

The error log:
```
3:31PM INF error from light block request from primary, removing... error="post failed: Post \"https://rpc.testnet.seda.xyz:443\": context deadline exceeded" height=452634 module=light primary=http{https://rpc.testnet.seda.xyz:443}
3:31PM ERR error on light block request from witness, removing... error="post failed: Post \"http://18.171.36.35:26657\": context deadline exceeded" module=light primary=http{http://18.171.36.35:26657}
3:31PM ERR failed to remove witnesses err="no witnesses connected. please reset light client" module=light witnessesToRemove=[0]
3:31PM ERR Can't verify err="failed to obtain the header at height #452634: post failed: Post \"http://18.171.36.35:26657\": context deadline exceeded" module=light
3:31PM INF failed to fetch and verify app hash err="failed to obtain the header at height #452634: post failed: Post \"http://18.171.36.35:26657\": context deadline exceeded" module=statesync
3:31PM INF Snapshot rejected format=3 hash=4F545689CF8A69D8E760E9178589D379FE77790AF43BAA974108FD67DEB1D83E height=451000 module=statesync
3:31PM INF VerifyHeader hash=797BDEA7C8E98C90BEAE34F0D666C5C9D61464CEF910F6ECE6ABFBEC4A2D07CE height=449001 module=light
3:32PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=10 numToDial=0
```

In short, snapshot sync and state sync should work without relying on external validators.

**Comment by DeshErBojhaa** [comment]
### To generate snapshots on dev nodes

For all nodes in the dev env:
1. Connect to the node.
2. Edit `[state-sync]` in `app.toml`
  a. snapshot-interval = 10 [later we will increase the interval]
  b. snapshot-keep-recent = 2
3. Restart the chain `sudo systemctl restart seda-node.service`
4. Check new blocks are being created `journalctl -u seda-node.service -f`
5. Wait for a while and ensure there are `snapshot-keep-recent` number of snapshots in the `data/snapshot` folder.

-------------

### To state sync using the snapshot
Our local chain was 
1. Check out the exact version locally. [ex: `git checkout v0.0.7`]
2. `make build`
3. Join the devnet.
  a. Remove the .sedad folder. [most likely located in the home directory]
  b. `sedad join test-node --network devnet` this will get the genesis.
4. Get trust height and trust hash `curl -s ip_dev_node_1:26657/block |
  jq -r '.result.block.header.height + "\n" + .result.block_id.hash'`
5. Update the `[statesync]` in the `config.toml` located in the .sedad folder
  a. `enable = true`
  b. `rpc_servers = ip_dev_node_1:26657,ip_dev_node_2:26657`
  c. `trust_height` and `trust_hash` from step 4.
  d. `trust_period = "336h0m0s"` [should usually be about 2/3 of the unbonding time (~2 weeks) during which they can be financially punished (slashed) for misbehavior.]
6. Run the chain locally `build/sedad`
7. Check logs to make sure it's catching up with the latest blocks from the dev net.



--------------
After we are satisfied with the whole process, we should increase the snapshot interval.
Increase the interval from 10 -> 1000 in 2.a

**Comment by DeshErBojhaa** [comment]
## Import things to take into account

If you have multiple nodes, put the more reliable nodes ip first.

```toml
[statesync]
enable = true
rpc_servers = "13.41.125.154:26657,18.171.36.35:26657"

trust_height = 515687
trust_hash = "BB9C5XXXXX742F8"
trust_period = "168h0m0s"
```

`13.41.125.154` is first because it's more reliable.
