### ISSUE TITLE
📚 Double check inflation parameters

### ISSUE THREAD

**Issue by mariocao** [sedaprotocol/seda-chain#26]
## ✨ Feature

Disable the community tax by properly setting the `community_tax` parameter in the distribution module and check that inflation is set to 5%.

## Motivation

There is no clear need for a community tax within the SEDA Protocol.

## Implementation

Configure the `community_tax` parameter to zero.

Reference: https://docs.cosmos.network/main/modules/distribution#params

**Comment by gluax** [comment]
Re-opened: We should check inflation settings; it should be set to 5% for now.

**Comment by mariocao** [comment]
We are closing this issue for now as inflation parameters are well set, but they might change after further discussions.
