### ISSUE TITLE
✨ Add filter types `Mode` and `StdDev`

### ISSUE THREAD

**Issue by hacheigriega** [sedaprotocol/seda-chain#284]
## ✨ Feature

The chain currently only supports `None` filter, but we hope to add two new filters: `Mode` and `StdDev`. Some preliminary work was done in PR #280 but was removed to prioritize solidifying the minimum tally requirement first. Both the corresponding unit testing and integration testing should be updated to cover these new types.

**Comment by DeshErBojhaa** [comment]
Mode is implemented here https://github.com/sedaprotocol/seda-chain/pull/290
