### ISSUE TITLE
♻️ Tally Endblock refactoring

### ISSUE THREAD

**Issue by hacheigriega** [sedaprotocol/seda-chain#291]
## ♻️ Refactor

Address the issues identified during tally implementation:

- [x] First, we have noticed that an error, not just a panic, in the end blocker logic halts the chain with a consensus failure. We need to research into how errors and panics are supposed to be handled in the end blocker and possibly implement a helper to reconcile an end blocker error without halting the chain. Relevant resources:

- https://docs.cosmos.network/main/build/building-apps/security-part-1#in-protocol-panics
- https://github.com/osmosis-labs/osmosis/blob/b0aee0006ce55d0851773084bd7880db7e32ad70/osmoutils/cache_ctx.go#L13-L44

- [x] Emit events during tally process.
- [ ] Check code coverage and add unit tests to achieve a good test coverage. 
  - Make sure to test edge cases.
  - Utilize go mock to intercept and check arguments. See https://pkg.go.dev/github.com/golang/mock/gomock?utm_source=godoc#Call.Do 
  - Add CodeQL analysis to detect and check all possible points of panic in the end blocker.
- [ ] PostDataResults's message structure does not seem to support submission of multiple results at once. (contract needs update - perhaps not a priority)
- [ ] Use limits when fetching tally list from contract.

**Comment by Thomasvdam** [comment]
@hacheigriega does it make sense to move the open points to a new issue and close this one?

**Comment by hacheigriega** [comment]
Agreed. Closing this in favor of #313, which elaborates on the last three tasks.
