### ISSUE TITLE
Research key workflow of cosmos sdk

### ISSUE THREAD

**Issue by DeshErBojhaa** [sedaprotocol/seda-chain#292]
- [x] How validator are created
- [x] How initial pub/private keys are stored
- [x] How can we use those functionality in our case

**Comment by hacheigriega** [comment]
Make sure to check the code in `x/staking` and `x/randomness` in our repo too in case it helps!

**Comment by DeshErBojhaa** [comment]
Summary of the findings are put in this [notion page.](https://www.notion.so/sedaprotocol/PKI-public-key-registry-notes-dd743ea615f8428aa2ef2f7a1436222d?pvs=4)
Implementation is wip here: https://github.com/sedaprotocol/seda-chain/pull/299/files
