### ISSUE TITLE
🐛 Static ARM build crashes on tally

### ISSUE THREAD

**Issue by Thomasvdam** [sedaprotocol/seda-chain#298]
## 🐛 Bug Report

When the node encounters a block where the tally VM is invoked the process stops with a core dump on the first call into the tally VM.

This does not happen with a dynamically linked build of the exact same version, built by checking out the tag and running `make build`.

## Steps to Reproduce

Set up the node as usual and attempt to sync up with a network that has DRs with enough reveals to proceed to the tally stage.

#### Stack trace & error message

Logs taken from journalctl:
```
Jul 04 08:24:41 cosmovisor[36022]: 8:24AM INF received proposal module=consensus proposal="Proposal{3113/0 (92CE960CC2FF34095E6F573900059B3CD29C4252C89FB4E3CF4EFD2014BBE2A8:1:E0A7869C6087, -1) 18C405B66B5D @ 2024-07-04T08:24:41.662000716Z}" proposer=470887968BE1D4E8370874AE0558C6C68AF70A25
Jul 04 08:24:41 cosmovisor[36022]: 8:24AM INF received complete proposal block hash=92CE960CC2FF34095E6F573900059B3CD29C4252C89FB4E3CF4EFD2014BBE2A8 height=3113 module=consensus
Jul 04 08:24:41 cosmovisor[36022]: 8:24AM INF finalizing commit of block hash=92CE960CC2FF34095E6F573900059B3CD29C4252C89FB4E3CF4EFD2014BBE2A8 height=3113 module=consensus num_txs=1 root=A2B6050363AC67CB8A36B511A80EB96B77DE88BC915F01176409F8EA02B71F3B
Jul 04 08:24:41 cosmovisor[36022]: 8:24AM INF non-empty tally list - starting tally process module=x/wasm-storage
Jul 04 08:24:41 cosmovisor[36022]: 8:24AM INF executing tally VM arguments=["","[{\"reveal\":[84,104,105,115,32,105,115,32,97,32,68,82,32,101,120,101,99,117,116,105,111,110,32,114,101,115,117,108,116],\"salt\":[],\"exit_code\":0,\"gas_used\":\"0\"}]","[0]"] consensus=true module=x/wasm-storage request_id=88c7c0bf0f22b71328fccc2180871f600f50733565afe3d9bfb80f46753fbd9d tally_wasm_hash=e728da7f1457fcf1110f8664e1962d0076d1f301cef09e5f130b9a7d60ccef06
Jul 04 08:26:07 cosmovisor[36016]: Error: signal: aborted (core dumped)
Jul 04 08:26:07 cosmovisor[36016]: 8:26AM ERR error="signal: aborted (core dumped)" module=cosmovisor
```

## Expected Behaviour

The node should not crash when executing tally WASM binaries.

## Your Environment

./sedad version: 0.2.0-dev.2, taken from Github release (statically compiled)
Architecture: aarch64

**Comment by gluax** [comment]
So, I am adding some context to the issue itself here.

You cannot have multiple libraries from `rust` statically linked to the same target; you can read more about that [here](https://users.rust-lang.org/t/linking-more-than-one-rustc-compiled-static-libraries-in-a-c-project/89778), and with the `rust` issue, the link.

Since `cosmwasm` also uses `rust` to generate their library for the `cosmwasm` VM. So mixed with ours, and boom, problems.

This is flexible, but it will be an **effort** to get working.

**Comment by gluax** [comment]
Our next guess is that wasmer is not playing nicely to execute in parallel from a static context. 
So we should try to remove cosmwasm VM from the chain and plug in static data(for contract calls) where necessary to see if that will work. 

@hacheigriega how much of a pain would this be?

**Comment by hacheigriega** [comment]
We have determined that Rosetta is the source of the issue. It appears that importing Rosetta and statically compiling the program leads to a symbol collision. The problem can be replicated using the following sample program:

```
package main

import (
	"fmt"
	"os"
	_ "github.com/cosmos/rosetta/cmd"
	"github.com/sedaprotocol/seda-wasm-vm/tallyvm"
)

func main() {
	tallyWasm, err := os.ReadFile("./testwasm.wasm")
	if err != nil {
		panic(err)
	}

	vmRes := tallyvm.ExecuteTallyVm(tallyWasm, []string{"asdf"}, map[string]string{
		"VM_MODE":   "tally",
		"CONSENSUS": fmt.Sprintf("%v", true),
	})
	fmt.Println(vmRes)
}
```

**Comment by Thomasvdam** [comment]
Closing this as with #321 we introduced a workaround.
