### ISSUE TITLE
🔧 Explore and document different forms of testing

### ISSUE THREAD

**Issue by hacheigriega** [sedaprotocol/seda-chain#30]
## 🔧 Chore

Cosmos-SDK support various forms of [testing](https://docs.cosmos.network/main/building-modules/testing) such as the following:

- Unit testing
- Integration testing
- In-process multi-validator testnet
- Simulation (fuzzing)
- E2e testing

Currently, unit testing and integration testing are of less importance since we haven't implemented any custom modules. We could also consider creating a script for deploying a test network across multiple clusters.

**Comment by JeancarloBarrios** [comment]
At some point if we want we could also include model-based testing with [TLA](https://lamport.azurewebsites.net/tla/tla.html)+ or [Quint](https://github.com/informalsystems/quint). The informal team has created some really cool tools like Apalache https://github.com/informalsystems/apalache and Atomkraft https://github.com/informalsystems/atomkraft
