### ISSUE TITLE
🔧 Disable wasm_storage pruning

### ISSUE THREAD

**Issue by Thomasvdam** [sedaprotocol/seda-chain#330]
## 🔧 Chore

Until we implement renewal of the expiration date when DR WASMs get used we should disable state pruning. 

## Motivation

This prevents DRs from not working all of a sudden. 

## Implementation

- Either set the default TTL to infinity, or disable the feature entirely.
- Create/edit follow up issue to implement state pruning.

**Comment by hacheigriega** [comment]
Closed by #346
