### ISSUE TITLE
♻️ SEDA signer registration without restart

### ISSUE THREAD

**Issue by hacheigriega** [sedaprotocol/seda-chain#375]
## ♻️ Refactor

Currently the application at startup reads the SEDA key file and registers the `ExtendVote` ABCI method only if the read is successful. If the SEDA key file is generated after the startup, the application has to be restarted. To avoid the need for restarting the app, we could

- Check for the SEDA key file every time the `ExtendVote` method runs if the signer is `nil`.
- Or "dynamically watch" the file to support key rotation without a restart as well

The issue also calls for clarifying the SEDA key file configurations. Currently the application assumes that the key file is placed in the same directory as the consensus key file.

**Comment by mariocao** [comment]
Before tackling this issue we should formalize the node operator onboarding.
