### ISSUE TITLE
✨Node monitoring 

### ISSUE THREAD

**Issue by hacheigriega** [sedaprotocol/seda-chain#74]
## ✨ Feature

Implement a live monitoring system, complete with a detection mechanism and alert system to identify any potential issues with the chain.

## Motivation

Chain operation always involves a risk of undesirable events like node failures or chain halts. It is crucial that we detect a problem as quickly as possible to minimize down time.

Helpful article on this: https://artifact-staking.medium.com/setting-up-validator-monitoring-for-cosmos-sdk-blockchains-8ee1676eb4b0

**Comment by mariocao** [comment]
Closing it as we successfully deployed the following components:
- Node exporter for Prometheus metrics
- Prometheus to collect data from nodes and node exporter
- Grafana to display metrics and alert when required
- Alerts
